### ISSUE TITLE
Can`t activate plugin due to Fatal error

### ISSUE THREAD

**Issue by spiatrenka** [Binternet/WordPress-Plugin-Categories-Multiple-Images#1]
I tried to install plugin on Wordpress 4.3.1, but I couldn`t do it due to fatal error:
Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected end of file in /www/wordpress.dev/wp-content/plugins/categories-multiple-images/categories-multiple-images.php on line 462

**Comment by ghost** [comment]
There you go mate. :smile:
